name: ikinokat
description: ikinokat wholesale e-commerce application.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  get: ^3.26.0
  flutter_launcher_icons: ^0.7.0
  flutter_swiper: ^1.1.6
  provider: ^4.3.3
  dio: ^3.0.10
  cached_network_image: ^2.5.0
  image_picker: ^0.6.7+22
  shared_preferences: ^0.5.12+4
  connectivity: ^2.0.2
  flutter_screenutil: ^1.0.2
  flutter_splash_screen: ^0.1.0
  pull_to_refresh: ^1.6.4
  flutter_svg: ^0.19.2
  url_launcher: ^5.7.10
  oktoast: ^2.3.2
  flutter_slidable: ^0.5.7
  multi_image_picker: ^4.8.0
  flutter_absolute_path: ^1.0.6
  http_parser: ^3.1.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 500
